import { app, BrowserWindow, dialog, ipcMain, shell } from 'electron'
import { join } from 'path'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import * as db from './database'
import { tailorDocument, generateFollowUpMessage, regenerateSection } from './ai'
import { scrapeJobFromUrl } from './jobScraper'
import { scanAllBoards, scoreCompatibility } from './jobSearch'
import { PDFParse } from 'pdf-parse'
import mammoth from 'mammoth'
import type {
  ApiModelConfig,
  Application,
  CreateJobInput,
  FollowUp,
  Interview,
  Job,
  JobStatus,
  ScanFilters,
  ScanResult,
  Settings,
  TailorRequest
} from './types'

// Module-level scan state — survives tab switches in the renderer
let _scanState: { scanning: boolean; progress: string[]; result: ScanResult | null; startedAt: number | null } = {
  scanning: false,
  progress: [],
  result: null,
  startedAt: null
}

function createWindow(): void {
  const mainWindow = new BrowserWindow({
    width: 1280,
    height: 860,
    minWidth: 960,
    minHeight: 640,
    show: false,
    title: 'Apply Assistant',
    titleBarStyle: 'hiddenInset',
    backgroundColor: '#0f1117',
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      sandbox: false,
      contextIsolation: true,
      nodeIntegration: false
    }
  })

  mainWindow.on('ready-to-show', () => {
    mainWindow.show()
  })

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url)
    return { action: 'deny' }
  })

  if (process.env.ELECTRON_RENDERER_URL) {
    mainWindow.loadURL(process.env.ELECTRON_RENDERER_URL)
  } else {
    mainWindow.loadFile(join(__dirname, '../renderer/index.html'))
  }
}

function registerIpc(): void {
  ipcMain.handle('dashboard:stats', () => db.getDashboardStats())

  ipcMain.handle('jobs:list', (_e, status?: JobStatus) => db.listJobs(status))
  ipcMain.handle('jobs:get', (_e, id: number) => db.getJob(id))
  ipcMain.handle('jobs:create', (_e, input: CreateJobInput) => {
    const dup = db.findDuplicateJob(input)
    if (dup) throw new Error(`Job already exists: ${dup.company} — ${dup.title}`)
    const job = db.createJob(input)
    autoGenerateDocuments(job)
    return job
  })
  ipcMain.handle('jobs:update', (_e, id: number, fields: Partial<CreateJobInput & { status: JobStatus }>) =>
    db.updateJob(id, fields)
  )
  ipcMain.handle('jobs:delete', (_e, id: number) => db.deleteJob(id))
  ipcMain.handle('jobs:search', (_e, query: string) => db.searchJobs(query))
  ipcMain.handle('jobs:importFromUrl', async (_e, url: string) => {
    const input = await scrapeJobFromUrl(url)
    const dup = db.findDuplicateJob(input)
    if (dup) throw new Error(`Job already exists: ${dup.company} — ${dup.title}`)
    const job = db.createJob(input)
    autoGenerateDocuments(job)
    return job
  })

  ipcMain.handle('jobs:batchScore', () => {
    const settings = db.getSettings()
    const baseCv = settings.base_cv || ''
    const jobs = db.listJobs()
    for (const job of jobs) {
      if (job.score != null) continue
      const desc = job.description || ''
      const score = scoreCompatibility(job.title, desc, baseCv)
      db.updateJob(job.id, { score })
    }
  })

  ipcMain.handle('jobs:scanBoards', async (e, filters?: ScanFilters) => {
    _scanState.scanning = true
    _scanState.progress = []
    _scanState.result = null
    _scanState.startedAt = Date.now()
    try {
      const result = await scanAllBoards(filters, (msg) => {
        _scanState.progress.push(msg)
        e.sender.send('scan:progress', msg)
      }, autoGenerateDocuments)
      _scanState.result = result
      return result
    } finally {
      _scanState.scanning = false
      _scanState.startedAt = null
    }
  })

  ipcMain.handle('scan:status', () => ({
    scanning: _scanState.scanning,
    progress: [..._scanState.progress],
    result: _scanState.result,
    startedAt: _scanState.startedAt
  }))

  ipcMain.handle('scan:clearResult', () => {
    _scanState.result = null
    _scanState.progress = []
  })

  ipcMain.handle('documents:list', (_e, jobId?: number) => db.listDocuments(jobId))
  ipcMain.handle('documents:create', (_e, type: 'cv' | 'cover_letter', title: string, content: string, jobId?: number) =>
    db.createDocument(type, title, content, jobId)
  )
  ipcMain.handle('documents:update', (_e, id: number, title: string, content: string) =>
    db.updateDocument(id, title, content)
  )
  ipcMain.handle('documents:delete', (_e, id: number) => db.deleteDocument(id))
  ipcMain.handle('documents:regenerateSection', async (_e, documentId: number, sectionName: string, jobId: number) =>
    regenerateSection(documentId, sectionName, jobId)
  )
  ipcMain.handle('documents:exportPdf', async (_e, title: string, content: string, docType?: string, company?: string, position?: string) => {
    const win = new BrowserWindow({ show: false, webPreferences: { contextIsolation: true, nodeIntegration: false } })

    function stripMarkdown(s: string): string {
      return s.replace(/\*\*(.+?)\*\*/g, '$1').replace(/\*(.+?)\*/g, '$1').replace(/__(.+?)__/g, '$1').replace(/_(.+?)_/g, '$1')
    }

    const sectionHeaders = new Set([
      'professional summary', 'summary', 'profile',
      'core competencies', 'competencies', 'skills', 'qualifications', 'technical skills',
      'professional experience', 'experience', 'work history', 'work experience',
      'education',
      'certifications', 'languages', 'interests', 'skills & interests', 'skills and interests',
      'projects', 'project experience',
      'leadership & activities', 'leadership and activities', 'activities', 'leadership',
      'publications', 'honors & awards', 'honors and awards', 'awards',
      'additional information', 'additional'
    ])

    function isHeader(s: string): boolean {
      const cleaned = stripMarkdown(s).toLowerCase().trim()
      return sectionHeaders.has(cleaned) || /^[a-z\s&]+$/.test(cleaned) && sectionHeaders.has(cleaned.replace(/[^a-z\s&]/g, '').trim())
    }

    const lines = content.split('\n')
    let htmlBody = ''
    let headerCollected = false
    const headerLines: string[] = []
    let noBulletSection = false

    function esc(s: string) {
      return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    }

    const bulletVerbs = /^(accomplished|achieved|led|managed|developed|created|implemented|designed|built|launched|delivered|improved|reduced|increased|generated|established|negotiated|coordinated|directed|spearheaded|introduced|optimized|transformed|piloted|engineered|produced|executed|authored|published|presented|mentored|trained|recruited|hired|fostered|cultivated|prepared|conducted|analyzed|analysed|evaluated|assessed|facilitated|collaborated|organized|supervised|overhauled|streamlined|consolidated|architected|championed|drove|drafted|formulated|identified|integrated|maintained|monitored|performed|pioneered|promoted|recommended|scheduled|secured|solved|standardized|strengthened|taught|wrote)/i
    const noBulletSections = new Set(['skills & interests', 'skills and interests', 'skills', 'interests', 'certifications', 'languages', 'additional information', 'additional'])

    for (let i = 0; i < lines.length; i++) {
      const raw = lines[i]
      const trimmed = raw.trim()
      const cleaned = stripMarkdown(trimmed).trim()
      if (!cleaned) { htmlBody += '<div class="spacer"></div>\n'; continue }

      const sect = isHeader(trimmed)
      const hasTab = cleaned.includes('\t')
      const isBullet = /^[•\-*\d+.)\]\s]/.test(cleaned) || bulletVerbs.test(cleaned)

      if (sect) {
        const lower = stripMarkdown(trimmed).toLowerCase().trim()
        noBulletSection = noBulletSections.has(lower)
        if (!headerCollected) headerCollected = true
        htmlBody += `<div class="section-header">${esc(cleaned)}</div>\n`
        continue
      }

      if (!headerCollected) {
        if (isBullet) {
          headerCollected = true
        } else {
          if (headerLines.length < 3) { headerLines.push(cleaned); continue }
          else { headerCollected = true }
        }
      }

      if (isBullet) { htmlBody += `<div class="bullet">${esc(cleaned.replace(/^[•\-*\d+.)\]\s]+/, ''))}</div>\n`; continue }

      if (hasTab) {
        const parts = cleaned.split('\t')
        const label = parts[0].replace(/^\*+|\*+$/g, '').trim()
        htmlBody += `<div class="split-line"><span class="left">${esc(label)}</span><span class="right">${esc(parts.slice(1).join(' ').trim())}</span></div>\n`
      } else if (cleaned.includes('|') && cleaned.length < 120) {
        const parts = cleaned.split('|').map(s => s.replace(/^\*+|\*+$/g, '').trim())
        htmlBody += `<div class="split-line"><span class="left">${esc(parts[0])}</span><span class="right">${esc(parts.slice(1).join(' | '))}</span></div>\n`
      } else if (noBulletSection) {
        htmlBody += `<div class="body-line">${esc(cleaned)}</div>\n`
      } else {
        htmlBody += `<div class="bullet">${esc(cleaned)}</div>\n`
      }
    }

    const headerHtml = headerLines.length > 0
      ? `<div class="header">${headerLines.map((l, j) => j === 0 ? `<div class="name">${esc(l)}</div>` : `<div class="contact">${esc(l)}</div>`).join('\n')}</div>`
      : ''

    const fullHtml = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  @page { margin: 0.6in 0.7in; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Calibri, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11pt; line-height: 1.2; color: #000; }
  .header { text-align: center; margin-bottom: 10px; }
  .name { font-size: 12pt; font-weight: bold; }
  .contact { font-size: 10pt; color: #222; }
  .section-header { text-align: center; font-weight: bold; font-size: 11pt; margin-top: 12px; margin-bottom: 3px; }
  .split-line { margin-bottom: 1px; }
  .split-line .left { font-weight: bold; }
  .split-line .right { float: right; }
  .bullet { margin-bottom: 1px; padding-left: 20px; text-indent: -10px; }
  .bullet::before { content: "• "; }
  .body-line { margin-bottom: 1px; }
  .spacer { height: 6px; }
</style></head>
<body>
${headerHtml}
${htmlBody}
</body>
</html>`
    await win.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(fullHtml))
    const pdf = await win.webContents.printToPDF({})
    win.close()
    const settings = db.getSettings()
    const userName = (settings.user_name || '').replace(/[^a-zA-Z0-9]/g, '')
    const safe = (s: string) => s.replace(/[^a-zA-Z0-9]/g, '')
    const nameParts = [userName, company ? safe(company) : '', position ? safe(position) : '', docType || title.replace(/ .*/, '')].filter(Boolean)
    const fileName = (nameParts.length > 1 ? nameParts.join('_') : `${title.replace(/[^a-z0-9]/gi, '_')}`) + '.pdf'
    const docsDir = join(app.getAppPath(), 'docs')
    if (!existsSync(docsDir)) mkdirSync(docsDir, { recursive: true })
    const { canceled, filePath } = await dialog.showSaveDialog({
      title: 'Save PDF',
      defaultPath: join(docsDir, fileName),
      filters: [{ name: 'PDF', extensions: ['pdf'] }]
    })
    if (canceled || !filePath) return null
    writeFileSync(filePath, pdf)
    return filePath
  })

  ipcMain.handle('applications:list', () => db.listApplications())
  ipcMain.handle('applications:getOrCreate', (_e, jobId: number) => db.getOrCreateApplication(jobId))
  ipcMain.handle('applications:update', (_e, id: number, fields: Partial<Application>) =>
    db.updateApplication(id, fields)
  )
  ipcMain.handle(
    'applications:markApplied',
    (_e, id: number, method: string, email?: string, name?: string) =>
      db.markApplied(id, method, email, name)
  )

  ipcMain.handle('followUps:list', (_e, includeCompleted?: boolean) =>
    db.listFollowUps(includeCompleted)
  )
  ipcMain.handle('followUps:create', (_e, appId: number, dueDate: string, type: FollowUp['type'], message?: string) =>
    db.createFollowUp(appId, dueDate, type, message)
  )
  ipcMain.handle('followUps:complete', (_e, id: number) => db.completeFollowUp(id))
  ipcMain.handle('followUps:generateMessage', async (_e, company: string, title: string, days: number) =>
    generateFollowUpMessage(company, title, days)
  )

  ipcMain.handle('interviews:list', (_e, upcomingOnly?: boolean) => db.listInterviews(upcomingOnly))
  ipcMain.handle(
    'interviews:create',
    (
      _e,
      appId: number,
      scheduledAt: string,
      type: Interview['type'],
      duration?: number,
      location?: string,
      interviewer?: string,
      notes?: string
    ) => db.createInterview(appId, scheduledAt, type, duration, location, interviewer, notes)
  )
  ipcMain.handle('interviews:update', (_e, id: number, fields: Partial<Interview>) =>
    db.updateInterview(id, fields)
  )

  ipcMain.handle('settings:get', () => db.getSettings())
  ipcMain.handle('settings:update', (_e, partial: Partial<Settings>) => db.updateSettings(partial))
  ipcMain.handle('settings:reset', () => db.resetSettings())
  ipcMain.handle('settings:importResume', async () => {
    const { canceled, filePaths } = await dialog.showOpenDialog({
      title: 'Import Resume',
      filters: [
        { name: 'Resume', extensions: ['pdf', 'docx'] }
      ],
      properties: ['openFile']
    })
    if (canceled || filePaths.length === 0) return null
    const filePath = filePaths[0]
    const ext = filePath.toLowerCase().slice(filePath.lastIndexOf('.'))
    const buffer = readFileSync(filePath)
    let text: string
    if (ext === '.pdf') {
      const pdf = new PDFParse(new Uint8Array(buffer))
      await pdf.load()
      text = await pdf.getText()
    } else if (ext === '.docx') {
      const result = await mammoth.extractRawText({ buffer: new Uint8Array(buffer) })
      text = result.value
    } else {
      return null
    }
    return text.trim()
  })

  ipcMain.handle('models:list', () => db.listApiModels())
  ipcMain.handle('models:save', (_e, models: ApiModelConfig[]) => db.saveApiModels(models))
  ipcMain.handle('models:add', (_e, model: Omit<ApiModelConfig, 'id'>) => db.addApiModel(model))
  ipcMain.handle('models:delete', (_e, id: string) => db.deleteApiModel(id))

  ipcMain.handle('ai:tailor', async (_e, request: TailorRequest) => tailorDocument(request))

  ipcMain.handle('db:clearSeenUrls', () => db.clearSeenUrls())
  ipcMain.handle('db:clearAllData', () => db.clearAllData())

  ipcMain.handle('shell:openExternal', (_e, url: string) => shell.openExternal(url))
}

async function autoGenerateDocuments(job: Job): Promise<void> {
  try {
    const app = db.getOrCreateApplication(job.id)
    const [cvResult, clResult] = await Promise.all([
      tailorDocument({ job_id: job.id, document_type: 'cv' }),
      tailorDocument({ job_id: job.id, document_type: 'cover_letter' })
    ])
    db.updateApplication(app.id, {
      cv_document_id: cvResult.document_id,
      cover_letter_document_id: clResult.document_id
    })
  } catch {
    // Silently fail — user can generate manually from the job detail page
  }
}

app.whenReady().then(() => {
  registerIpc()
  createWindow()

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})
